name: test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  chime-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
        # pytorch-version: [1.13.1, 2.1.2]
        #exclude:
        #  - python-version: '3.11'
        #    pytorch-version: 1.13.1
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - run: python -m pip install --upgrade pip
    # Default torch has GPU support and large binaries. CPU only is smaller.
    - run: pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
    - run: python -m pip install -e .[dev]
    - run: pytest tests/test_normalizer.py
